### PR TITLE
Fix for sym link issue

### PR DESCRIPTION
**Pull request by HarithaIBM**
Fix for https://github.com/ZOSOpenTools/whichport/issues/4

### CODE REVIEW

**Review by MikeFultonDev — APPROVED** [review]
LGTM - does this effect our testcase success rate? 
Should we add a test to bash and which for this to ensure we don't 'lose' the fix'?

**Comment by HarithaIBM** [comment]
> LGTM - does this effect our testcase success rate? Should we add a test to bash and which for this to ensure we don't 'lose' the fix'?

Yes, That will be better Mike, i will do that

**Comment by HarithaIBM** [comment]
> LGTM - does this effect our testcase success rate? Should we add a test to bash and which for this to ensure we don't 'lose' the fix'?

I have added test case for the same.

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Pull request merged**
